version: '2.3'
services:
  xl-deploy:
    image: xebialabsunsupported/xl-deploy:8.5.0-alpha.25-no-devops-as-code
    ports:
    - "4516:4516"
    volumes:
    - ./docker/volumes/xld/conf/deployit-license.lic:/opt/xebialabs/xl-deploy-server/conf/deployit-license.lic:ro
    - ./docker/volumes/xld/hotfix/plugins:/opt/xebialabs/xl-deploy-server/hotfix/plugins:ro
    # Workaround for bug (in XL Deploy?) that causes plugins to not function correctly if loaded from within the container
    - ./docker/volumes/xld/plugins:/opt/xebialabs/xl-deploy-server/plugins
    environment:
    - ADMIN_PASSWORD=admin

  xl-release:
    image: xebialabsunsupported/xl-release:8.5.0-alpha.22-no-devops-as-code
    ports:
    - "5516:5516"
    depends_on:
    - xl-deploy
    volumes:
    - ./docker/volumes/xlr/conf/xl-release-license.lic:/opt/xebialabs/xl-release-server/conf/xl-release-license.lic:ro
    - ./docker/volumes/xlr/hotfix:/opt/xebialabs/xl-release-server/hotfix:ro
    environment:
    - ADMIN_PASSWORD=admin

  xl-cli:
    build: docker/xl-cli
    depends_on:
    - xl-deploy
    - xl-release
    command: ["apply", "-v", "--xl-deploy-url", "http://xl-deploy:4516/", "--xl-release-url", "http://xl-release:5516/", "-f", "/data/config/configure-xl-devops-platform.yaml"]
    volumes:
    - .:/data:ro

  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    privileged: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment: # warning this potentially opens up a security hole :)
      - AUTH=1
      - BUILD=1
      - COMMIT=1
      - CONTAINERS=1
      - EVENTS=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PING=1
      - PLUGINS=1
      - POST=1
      - SECRETS=1
      - SERVICES=1
      - SWARM=1
      - SYSTEM=1
      - TASKS=1
      - VERSION=1
      - VOLUMES=1
